---

ntp:
  - server_ip: 4.4.4.4
    preferred: {}

  - server_ip: 5.5.5.5
    preferred: "True"

  - server_ip: 6.6.6.6
    preferred: {}


ospf:
  process_id: "IPvZero"
  router_id: "44.44.44.44"
  areas:
    - area: 0
      interfaces:
        - "GigabitEthernet0/0/0/3"
        - "GigabitEthernet0/0/0/4"
        - "GigabitEthernet0/0/0/5"

    - area: 51
      interfaces:
        - "GigabitEthernet0/0/0/8"

    - area: 431
      interfaces:
        - "GigabitEthernet0/0/0/15"

    - area: 99
      interfaces:
        - "GigabitEthernet0/0/0/10"
        - "GigabitEthernet0/0/0/11"


bgp:
  autonomous_system: 65001
  bgp_rid: 1.1.1.1
  networks:
    - network: "23.23.23.0"
      prefix: "24"
    - network: "24.24.24.0"
      prefix: "24"

  neighbors:
    - neighbor: 2.2.2.2
      remote_as: "65002"

    - neighbor: 3.3.3.3
      remote_as: "65003"
      keepalive: "15"
      hold-time: "45"

    - neighbor: 4.4.4.4
      remote_as: "65004"
      keepalive: "20"
      hold-time: "60"


ACLs:
  - acl_name: "LIST1"
    remarks:
      - sequence: 10
        statement: "~~ PERMITS WEB ACCESS FOR 192.168.1.1 -- 34.34.34.0/24 ~~"

      - sequence: 30
        statement: "~~ PERMITS IP TRAFFIC FROM 172.16.10.0/24 -- 32.32.32.0/24 ~~"

    rules:
      - sequence: 20
        grant: "permit"
        protocol: "tcp"
        source_address: "192.168.1.1"
        source_wildcard: "0.0.0.0"
        destination_address: "34.34.34.0"
        destination_wildcard: "0.0.0.255"
        destination_port: "www"
        destination_operator: "equal"

      - sequence: 40
        grant: "permit"
        protocol: "ip"
        source_address: "172.16.10.0"
        source_wildcard: "0.0.0.255"
        destination_address: "32.32.32.0"
        destination_wildcard: "0.0.0.255"


  - acl_name: "LIST2"
    remarks:
      - sequence: 10
        statement: "~~ PERMITS SSH ACCESS FOR 192.168.55.5 -- 34.34.34.0/24 ~~"

      - sequence: 30
        statement: "~~ PERMITS IP TRAFFIC FROM 172.25.10.0/24 -- ANYWHERE ~~"

    rules:
      - sequence: 20
        grant: "permit"
        protocol: "tcp"
        source_address: "192.168.55.5"
        source_wildcard: "0.0.0.0"
        destination_address: "34.34.34.0"
        destination_wildcard: "0.0.0.255"
        destination_port: 22
        destination_operator: "equal"

      - sequence: 40
        grant: "permit"
        protocol: "ip"
        source_address: "172.25.10.0"
        source_wildcard: "0.0.0.255"


  - acl_name: "LIST3"
    remarks:
      - sequence: 10
        statement: "~~ DENY ICMP TO 8.8.8.8 ~~"

      - sequence: 30
        statement: "PERMITS ALL OTHER TRAFFIC"

    rules:
      - sequence: 20
        grant: "deny"
        protocol: "icmp"
        destination_address: "8.8.8.8"
        destination_wildcard: "0.0.0.0"

      - sequence: 40
        grant: "permit"
        protocol: "ip"
